[package]
name = "solana_toolbox_endpoint"
description = "Toolbox for interacting with an arbitrary solana endpoint"
version = "0.1.36-solana-2.1.4"
edition = "2021"
license = "MIT"

[dependencies]
async-trait = "0.1.83"

bincode = "1.3.3"
serde = "1.0.216"
borsh = "1.5.3"
bytemuck = "1.21.0"

solana-client = "=2.1.4"
solana-program-test = "=2.1.4"
solana-program-runtime = "=2.1.4"
solana-sdk = "=2.1.4"

spl-token = { version = "4.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "6.0.0", features = [
    "no-entrypoint",
] }

[dev-dependencies]
tokio = "1.42.0"
