[package]
name = "solana_toolbox_endpoint"
description = "Toolbox for interacting with an arbitrary solana endpoint"
version = "0.1.15-solana-2.0.18"
edition = "2021"
license = "MIT"

[dependencies]
async-trait = "0.1.83"

bincode = "1.3.3"
serde = "1.0.216"
borsh = "1.5.3"

solana-client = "2.0.18"
solana-program-test = "2.0.18"
solana-sdk = "2.0.18"

spl-token = { version = "6.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "4.0.0", features = [
    "no-entrypoint",
] }
