[package]
name = "solana_toolbox_endpoint"
description = "Toolbox for interacting with an arbitrary solana endpoint"
version = "0.1.6-solana-1.18.26"
edition = "2021"
license = "MIT"

[dependencies]
async-trait = "0.1.83"
bincode = "1.3.3"
borsh = "1.5.3"
solana-client = "1.18.26"
solana-program-test = "1.18.26"
solana-sdk = "1.18.26"
tokio = "1.42.0"

spl-token = { version = "4.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "2.1", features = ["no-entrypoint"] }
