[package]
name = "solana_toolbox_endpoint"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
bincode = "1.3.3"
borsh = "1.5.3"
solana-client = "2.1.7"
solana-program-test = "2.1.7"
solana-sdk = "2.1.7"
tokio = "1.42.0"
