[package]
name = "solana_toolbox_endpoint"
description = "Toolbox for interacting with an arbitrary solana endpoint"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
async-trait = "0.1.83"
bincode = "1.3.3"
borsh = "1.5.3"
solana-client = "2.0.18"
solana-program-test = "2.0.18"
solana-sdk = "2.0.18"
tokio = "1.42.0"
