[package]
name = "solana_toolbox_anchor"
description = "Toolbox for interacting with an anchor programs using an endpoint"
version = "0.1.14-solana-2.0.18-anchor-0.30.1"
edition = "2021"
license = "MIT"

[dependencies]
solana-sdk = "=2.0.18"

anchor-lang = "=0.30.1"
anchor-spl = "=0.30.1"

solana_toolbox_endpoint = "=0.1.14-solana-2.0.18"
